import { assets } from '../bandAssets'

// Generated by scripts/gen_bands.py — do not hand-edit.
// Figma Frame 263 band "acara": y 6920..9960, height 3040 design px.
// x/y are band-local design px; `z` is the GLOBAL Figma child order, so layers still
// stack correctly against the bands above and below this one.
import type { BandLayer } from '../bandLayer'

export const BAND_TOP = 6920
export const BAND_HEIGHT = 3040

export const LAYERS: BandLayer[] = [
  { z: 67, id: "2755:611", src: assets['groom/parts/floral-pastel.webp'], x: 204, y: 2453, w: 844.409, h: 866.43, iw: 521.78, ih: 693, stack: 6, rotate: -39.78, flipY: true },
  { z: 68, id: "2755:612", src: assets['groom/parts/floral-pastel.webp'], x: 204, y: 2430, w: 844.409, h: 866.43, iw: 521.78, ih: 693, stack: 6, rotate: -140.22 },
  { z: 69, id: "2755:617", src: assets['groom/parts/floral-pastel.webp'], x: -453, y: 2464, w: 844.409, h: 866.43, iw: 521.78, ih: 693, stack: 6, rotate: -140.22 },
  { z: 70, id: "2755:618", src: assets['groom/parts/floral-pastel.webp'], x: -453, y: 2441, w: 844.409, h: 866.43, iw: 521.78, ih: 693, stack: 6, rotate: -39.78, flipY: true },
  { z: 75, id: "2750:539", src: assets['groom/parts/floral-pastel.webp'], x: 192, y: 1213, w: 844.409, h: 866.43, iw: 521.78, ih: 693, stack: 6, rotate: 39.78 },
  { z: 76, id: "2750:540", src: assets['groom/parts/floral-pastel.webp'], x: 192, y: 1236, w: 844.409, h: 866.43, iw: 521.78, ih: 693, stack: 6, rotate: 140.22, flipY: true },
  { z: 80, id: "2750:486", src: assets['acara/parts/event-arch.webp'], x: -207, y: 28, w: 983, h: 1458, fit: "fill" },
  { z: 81, id: "2750:525", src: assets['acara/parts/event-arch.webp'], x: -180, y: 1556, w: 983.011, h: 1458, fit: "fill", flipX: true },
  { z: 82, id: "2750:499", src: assets['acara/parts/event-ellipse.svg'], x: -131, y: 662, w: 832, h: 1014, fit: "fill" },
  { z: 83, id: "2750:526", src: assets['acara/parts/event-ellipse.svg'], x: -131, y: 2190, w: 832, h: 1014, fit: "fill" },
  { z: 84, id: "2750:490", src: assets['acara/parts/event-photo.webp'], x: 41, y: 1093, w: 513, h: 311, crop: { w: 100.02, h: 292.95, l: -0.01, t: -87.18 } },
  { z: 85, id: "2750:527", src: assets['acara/parts/event-photo.webp'], x: 41, y: 2621, w: 512.353, h: 311, flipX: true, crop: { w: 100.02, h: 292.95, l: -0.01, t: -87.18 } },
  { z: 86, id: "2750:522", src: assets['acara/parts/its-the-day.svg'], x: 144, y: 14, w: 439.289, h: 188.721, fit: "fill" },
  { z: 87, id: "2750:528", src: assets['acara/parts/its-the-day.svg'], x: 41, y: 1486, w: 439.289, h: 188.721, fit: "fill" },
]
