import { assets } from '../bandAssets'

// Generated by scripts/gen_bands.py — do not hand-edit.
// Figma Frame 263 band "bride": y 4150..5690, height 1540 design px.
// x/y are band-local design px; `z` is the GLOBAL Figma child order, so layers still
// stack correctly against the bands above and below this one.
import type { BandLayer } from '../bandLayer'

export const BAND_TOP = 4150
export const BAND_HEIGHT = 1540

export const LAYERS: BandLayer[] = [
  { z: 11, id: "2750:449", src: assets['groom/parts/profile-backdrop.webp'], x: -45.69, y: 437.18, w: 666.692, h: 467.216, flipX: true, maskBox: { src: assets['groom/parts/mask-profile.svg'], x: 24.192, y: 14.819, w: 595.5, h: 439.181 } },
  { z: 13, id: "2750:450", src: assets['groom/parts/floral-frame-profile.webp'], x: -150, y: 191, w: 860, h: 860 },
  { z: 17, id: "2750:451", src: assets['bride/parts/bride-photo.webp'], x: 48, y: 487, w: 500, h: 500, crop: { w: 100, h: 113.44, l: -2.24, t: -9.34 } },
  { z: 22, id: "2750:452", src: assets['groom/parts/cloud.webp'], x: 164, y: 859, w: 551.515, h: 280, a: 0.76 },
  { z: 24, id: "2750:453", src: assets['groom/parts/cloud.webp'], x: -203.52, y: 918, w: 551.515, h: 280, flipX: true },
  { z: 26, id: "2750:454", src: assets['groom/parts/cloud.webp'], x: -203.52, y: 918, w: 551.515, h: 280, flipX: true },
  { z: 28, id: "2750:455", src: assets['groom/parts/cloud.webp'], x: -196.52, y: 891, w: 551.515, h: 280, flipX: true },
  { z: 30, id: "2750:456", src: assets['groom/parts/cloud.webp'], x: 213.48, y: 911, w: 551.515, h: 280, flipX: true, stack: 4 },
  { z: 60, id: "2750:469", src: assets['hero/parts/floral-regency.webp'], x: -215, y: 640, w: 438, h: 438, flipX: true },
  { z: 62, id: "2750:470", src: assets['hero/parts/floral-regency.webp'], x: 355, y: 640, w: 438, h: 438 },
  { z: 108, id: "2756:629", src: assets['bride/parts/flying-swan.webp'], x: 363, y: 186, w: 233, h: 204, fit: "fill" },
]
