import { assets } from '../bandAssets'

// Generated by scripts/gen_bands.py — do not hand-edit.
// Figma Frame 263 band "closing": y 14180..16075, height 1895 design px.
// x/y are band-local design px; `z` is the GLOBAL Figma child order, so layers still
// stack correctly against the bands above and below this one.
import type { BandLayer } from '../bandLayer'

export const BAND_TOP = 14180
export const BAND_HEIGHT = 1895

export const LAYERS: BandLayer[] = [
  { z: 5, id: "2751:573", src: assets['hero/parts/floral-frame-top.webp'], x: -79, y: 652, w: 754, h: 754 },
  { z: 6, id: "2751:570", src: assets['closing/parts/watercolor-footer.webp'], x: -269, y: 1072, w: 1132, h: 849 },
  { z: 7, id: "2751:571", src: assets['quote/parts/floral-branch.webp'], x: -244, y: 905, w: 444.554, h: 167.032, iw: 438, ih: 146, rotate: 2.77 },
  { z: 8, id: "2751:578", src: assets['quote/parts/floral-branch.webp'], x: 399, y: 905, w: 444.554, h: 167.032, iw: 438, ih: 146, rotate: 177.23, flipY: true },
  { z: 42, id: "2751:588", src: assets['closing/parts/closing-backdrop.webp'], x: -79, y: 1085, w: 762, h: 491, maskBox: { src: assets['closing/parts/mask-closing.svg'], x: 215.873, y: 36.394, w: 321.67, h: 453.208 } },
  { z: 53, id: "2751:580", src: assets['hero/parts/couple-illustration.webp'], x: 55, y: 1133, w: 480, h: 480, maskBox: { src: assets['closing/parts/mask-bride-groom.svg'], x: 86, y: 0, w: 322, h: 430 } },
  { z: 98, id: "2751:576", src: assets['closing/parts/closing-arch.webp'], x: 47, y: 1016, w: 504, h: 629 },
  { z: 99, id: "2756:636", src: assets['closing/parts/closing-floral.webp'], x: 94, y: 1476, w: 408, h: 408 },
  { z: 102, id: "2752:596", src: assets['closing/parts/swans.webp'], x: -67, y: 841, w: 325.047, h: 274.462, iw: 294, ih: 234, rotate: -8.41, crop: { w: 189.8, h: 179.62, l: 0, t: -41.95 } },
  { z: 103, id: "2752:597", src: assets['closing/parts/swans.webp'], x: 350, y: 680, w: 279.796, h: 267.776, iw: 248.257, ih: 234, rotate: -8.41, crop: { w: 210.71, h: 168.39, l: -107.7, t: -35.05 } },
  { z: 106, id: "2755:621", src: assets['closing/parts/thankyou-ornament.webp'], x: 241, y: 35, w: 113.595, h: 141.592 },
  { z: 110, id: "2756:632", src: assets['closing/parts/thankyou-divider.svg'], x: 128, y: 214, w: 340, h: 58, fit: "fill" },
]
