// Generated by scripts/gen_bands.py — do not hand-edit.
// Figma Frame 263 band "gallery": y 9960..10850, height 890 design px.
// x/y are band-local design px; `z` is the GLOBAL Figma child order, so layers still
// stack correctly against the bands above and below this one.
import type { BandLayer } from '../bandLayer'

export const BAND_TOP = 9960
export const BAND_HEIGHT = 890

export const LAYERS: BandLayer[] = [

]
