// Generated by scripts/gen_bands.py — do not hand-edit.
// Figma Frame 263 band "gift": y 11280..12090, height 810 design px.
// x/y are band-local design px; `z` is the GLOBAL Figma child order, so layers still
// stack correctly against the bands above and below this one.
import type { BandLayer } from '../bandLayer'

export const BAND_TOP = 11280
export const BAND_HEIGHT = 810

export const LAYERS: BandLayer[] = [

]
