import { assets } from '../bandAssets'

// Generated by scripts/gen_bands.py — do not hand-edit.
// Figma Frame 263 band "groom": y 2620..4150, height 1530 design px.
// x/y are band-local design px; `z` is the GLOBAL Figma child order, so layers still
// stack correctly against the bands above and below this one.
import type { BandLayer } from '../bandLayer'

export const BAND_TOP = 2620
export const BAND_HEIGHT = 1530

export const LAYERS: BandLayer[] = [
  { z: 3, id: "2756:643", src: assets['hero/parts/floral-regency.webp'], x: -215, y: 206, w: 420, h: 420, flipX: true },
  { z: 4, id: "2756:644", src: assets['hero/parts/floral-regency.webp'], x: 381, y: 206, w: 420, h: 420 },
  { z: 10, id: "2748:402", src: assets['groom/parts/profile-backdrop.webp'], x: -43, y: 383.18, w: 666.692, h: 467.216, maskBox: { src: assets['groom/parts/mask-profile.svg'], x: 47, y: 14.819, w: 595.5, h: 439.181 } },
  { z: 12, id: "2748:394", src: assets['groom/parts/floral-frame-profile.webp'], x: -132, y: 137, w: 860, h: 860 },
  { z: 16, id: "2748:419", src: assets['groom/parts/groom-photo.webp'], x: 48, y: 433, w: 500, h: 500, crop: { w: 114.95, h: 129.79, l: -5.67, t: -26.23 } },
  { z: 21, id: "2745:105", src: assets['groom/parts/cloud.webp'], x: -137.52, y: 805, w: 551.515, h: 280, flipX: true, a: 0.76 },
  { z: 23, id: "2745:114", src: assets['groom/parts/cloud.webp'], x: 230, y: 864, w: 551.515, h: 280 },
  { z: 25, id: "2745:115", src: assets['groom/parts/cloud.webp'], x: 230, y: 864, w: 551.515, h: 280 },
  { z: 27, id: "2745:116", src: assets['groom/parts/cloud.webp'], x: 223, y: 837, w: 551.515, h: 280 },
  { z: 29, id: "2748:399", src: assets['groom/parts/cloud.webp'], x: -187, y: 857, w: 551.515, h: 280, stack: 4 },
  { z: 32, id: "2749:422", src: assets['groom/parts/floral-pastel.webp'], x: -519, y: 876, w: 844.409, h: 866.43, iw: 521.78, ih: 693, stack: 6, rotate: 140.22, flipY: true },
  { z: 33, id: "2749:432", src: assets['groom/parts/floral-pastel.webp'], x: -519, y: 899, w: 844.409, h: 866.43, iw: 521.78, ih: 693, stack: 6, rotate: 39.78 },
  { z: 59, id: "2748:395", src: assets['hero/parts/floral-regency.webp'], x: 355, y: 586, w: 438, h: 438 },
  { z: 61, id: "2748:396", src: assets['hero/parts/floral-regency.webp'], x: -215, y: 586, w: 438, h: 438, flipX: true },
  { z: 65, id: "2749:436", src: assets['groom/parts/floral-pastel.webp'], x: 230, y: 1175, w: 844.409, h: 866.43, iw: 521.78, ih: 693, stack: 6, rotate: 39.78 },
  { z: 66, id: "2749:437", src: assets['groom/parts/floral-pastel.webp'], x: 230, y: 1198, w: 844.409, h: 866.43, iw: 521.78, ih: 693, stack: 6, rotate: 140.22, flipY: true },
]
