import { assets } from '../bandAssets'

// Generated by scripts/gen_bands.py — do not hand-edit.
// Figma Frame 263 band "hero": y 0..1110, height 1110 design px.
// x/y are band-local design px; `z` is the GLOBAL Figma child order, so layers still
// stack correctly against the bands above and below this one.
import type { BandLayer } from '../bandLayer'

export const BAND_TOP = 0
export const BAND_HEIGHT = 1110

export const LAYERS: BandLayer[] = [
  { z: 1, id: "2756:647", src: assets['hero/parts/floral-frame-top.webp'], x: -89, y: -161, w: 756, h: 756 },
  { z: 14, id: "2746:363", src: assets['hero/parts/arch-wedding.webp'], x: -65, y: 306, w: 726, h: 635, fit: "fill" },
  { z: 50, id: "2747:381", src: assets['hero/parts/floral-regency.webp'], x: -210, y: 88, w: 420, h: 420, flipX: true },
  { z: 51, id: "2747:382", src: assets['hero/parts/floral-regency.webp'], x: 386, y: 69, w: 420, h: 420 },
  { z: 52, id: "2747:383", src: assets['hero/parts/podium.webp'], x: -49, y: 849, w: 694, h: 218, fit: "fill", filter: "drop-shadow(calc(-1 * var(--px)) calc(-15 * var(--px)) calc(17 * var(--px)) rgba(255, 247, 240, 0.41)) drop-shadow(calc(-4 * var(--px)) calc(-61 * var(--px)) calc(30 * var(--px)) rgba(255, 247, 240, 0.36)) drop-shadow(calc(-8 * var(--px)) calc(-137 * var(--px)) calc(41 * var(--px)) rgba(255, 247, 240, 0.21))" },
  { z: 54, id: "2746:364", src: assets['hero/parts/couple-illustration.webp'], x: 41, y: 482, w: 515, h: 515 },
  { z: 55, id: "2747:384", src: assets['hero/parts/floral-regency.webp'], x: 437, y: 782, w: 318, h: 318 },
  { z: 56, id: "2747:385", src: assets['hero/parts/floral-regency.webp'], x: -159, y: 782, w: 318, h: 318, flipX: true },
]
