import { assets } from '../bandAssets'

// Generated by scripts/gen_bands.py — do not hand-edit.
// Figma Frame 263 band "quote": y 1110..2620, height 1510 design px.
// x/y are band-local design px; `z` is the GLOBAL Figma child order, so layers still
// stack correctly against the bands above and below this one.
import type { BandLayer } from '../bandLayer'

export const BAND_TOP = 1110
export const BAND_HEIGHT = 1510

export const LAYERS: BandLayer[] = [
  { z: 18, id: "2745:69", src: assets['quote/parts/quote-card.svg'], x: 35.8, y: 258, w: 525.407, h: 886, fit: "fill" },
  { z: 57, id: "2748:387", src: assets['quote/parts/quote-frame.webp'], x: -275, y: 10, w: 1147, h: 1147 },
  { z: 77, id: "2749:431", src: assets['quote/parts/quote-ornament.svg'], x: 169, y: 1261, w: 258, h: 193, fit: "fill" },
  { z: 78, id: "2750:472", src: assets['quote/parts/floral-branch.webp'], x: -140, y: 326, w: 438, h: 146 },
  { z: 79, id: "2750:473", src: assets['quote/parts/floral-branch.webp'], x: 298, y: 326, w: 438, h: 146, flipX: true },
  { z: 107, id: "2755:625", src: assets['hero/parts/title-ornament.svg'], x: 103, y: 20, w: 390.432, h: 67.026, fit: "fill" },
]
