// Generated by scripts/gen_bands.py — do not hand-edit.
// Figma Frame 263 band "rsvp": y 12090..12780, height 690 design px.
// x/y are band-local design px; `z` is the GLOBAL Figma child order, so layers still
// stack correctly against the bands above and below this one.
import type { BandLayer } from '../bandLayer'

export const BAND_TOP = 12090
export const BAND_HEIGHT = 690

export const LAYERS: BandLayer[] = [

]
