import { assets } from '../bandAssets'

// Generated by scripts/gen_bands.py — do not hand-edit.
// Figma Frame 263 band "savedate": y 5690..6920, height 1230 design px.
// x/y are band-local design px; `z` is the GLOBAL Figma child order, so layers still
// stack correctly against the bands above and below this one.
import type { BandLayer } from '../bandLayer'

export const BAND_TOP = 5690
export const BAND_HEIGHT = 1230

export const LAYERS: BandLayer[] = [
  { z: 9, id: "2750:474", src: assets['savedate/parts/countdown-illustration.webp'], x: -50, y: 356, w: 692, h: 692 },
  { z: 35, id: "2745:167", src: assets['savedate/parts/countdown-ellipse.svg'], x: -120, y: 271, w: 832, h: 1014, fit: "fill" },
  { z: 71, id: "2755:604", src: assets['groom/parts/floral-pastel.webp'], x: -497, y: 388, w: 844.409, h: 866.43, iw: 521.78, ih: 693, stack: 6, rotate: 39.78 },
  { z: 72, id: "2755:605", src: assets['groom/parts/floral-pastel.webp'], x: -497, y: 411, w: 844.409, h: 866.43, iw: 521.78, ih: 693, stack: 6, rotate: 140.22, flipY: true },
  { z: 73, id: "2755:607", src: assets['groom/parts/floral-pastel.webp'], x: 220, y: 377, w: 844.409, h: 866.43, iw: 521.78, ih: 693, stack: 6, rotate: 140.22, flipY: true },
  { z: 74, id: "2755:608", src: assets['groom/parts/floral-pastel.webp'], x: 220, y: 400, w: 844.409, h: 866.43, iw: 521.78, ih: 693, stack: 6, rotate: 39.78 },
  { z: 104, id: "2755:600", src: assets['savedate/parts/border.webp'], x: -28, y: 21, w: 656.902, h: 367 },
  { z: 109, id: "2756:630", src: assets['savedate/parts/flying-swan-2.webp'], x: 71, y: 944, w: 369, h: 275, flipX: true, crop: { w: 100.17, h: 178.57, l: -0.08, t: -78.57 } },
]
