import { assets } from '../bandAssets'

// Generated by scripts/gen_bands.py — do not hand-edit.
// Figma Frame 263 band "video": y 10850..11280, height 430 design px.
// x/y are band-local design px; `z` is the GLOBAL Figma child order, so layers still
// stack correctly against the bands above and below this one.
import type { BandLayer } from '../bandLayer'

export const BAND_TOP = 10850
export const BAND_HEIGHT = 430

export const LAYERS: BandLayer[] = [
  { z: 43, id: "2745:284", src: assets['video/parts/video-thumb.webp'], x: 8, y: 23, w: 584, h: 329, radius: 23, crop: { w: 102.08, h: 331.16, l: -1.07, t: -79.75 } },
]
