// Generated by scripts/gen_bands.py — do not hand-edit.
// Figma Frame 263 band "video": y 10850..11280, height 430 design px.
// x/y are band-local design px; `z` is the GLOBAL Figma child order, so layers still
// stack correctly against the bands above and below this one.
import type { BandLayer } from '../bandLayer'

export const BAND_TOP = 10850
export const BAND_HEIGHT = 430

export const LAYERS: BandLayer[] = [

]
