import { assets } from '../bandAssets'

// Generated by scripts/gen_bands.py — do not hand-edit.
// Figma Frame 263 band "wish": y 12780..14180, height 1400 design px.
// x/y are band-local design px; `z` is the GLOBAL Figma child order, so layers still
// stack correctly against the bands above and below this one.
import type { BandLayer } from '../bandLayer'

export const BAND_TOP = 12780
export const BAND_HEIGHT = 1400

export const LAYERS: BandLayer[] = [
  { z: 2, id: "2756:646", src: assets['wish/parts/floral-frame-wishes.webp'], x: -34, y: 854, w: 677, h: 677 },
  { z: 105, id: "2755:619", src: assets['wish/parts/wishes-footer.webp'], x: -38, y: 1014, w: 830, h: 465 },
]
